[package]
name = "finance_as_code_budget"
version = "0.1.0"
edition = "2024"

[features]
source_lunchflow = ["dep:finance_as_code_budget_source_lunchflow"]
source_mbank = ["dep:finance_as_code_budget_source_mbank"]
sink_treeline = ["__sink_treeline__nonbundled_duckdb", "finance_as_code_budget_sink_treeline/duckdb-bundled"]
__sink_treeline__nonbundled_duckdb = ["dep:finance_as_code_budget_sink_treeline"]
sink_lunchmoney = ["dep:finance_as_code_budget_sink_lunchmoney"]

__all_nonbundled_duckdb = ["__sink_treeline__nonbundled_duckdb", "sink_lunchmoney", "source_lunchflow", "source_mbank"]
all = ["__all_nonbundled_duckdb", "sink_treeline"]

[dependencies]
finance_as_code_budget_core.workspace = true
finance_as_code_budget_source_lunchflow = { workspace = true, optional = true }
finance_as_code_budget_source_mbank = { workspace = true, optional = true }
finance_as_code_budget_sink_treeline = { workspace = true, optional = true }
finance_as_code_budget_sink_lunchmoney = { workspace = true, optional = true }
rootcause.workspace = true
colog.workspace = true
log.workspace = true
