[package]
name = "finance_as_code_budget"
version = "0.1.0"
edition = "2024"

[features]
source_lunchflow = ["dep:finance_as_code_budget_source_lunchflow"]
source_mbank = ["dep:finance_as_code_budget_source_mbank"]
sink_treeline = ["dep:finance_as_code_budget_sink_treeline"]
sink_lunchmoney = ["dep:finance_as_code_budget_sink_lunchmoney"]

all = ["sink_lunchmoney", "source_lunchflow", "source_mbank", "sink_treeline"]

bundled_db = ["dep:duckdb"]
all_with_db = ["all", "bundled_db"]

[dependencies]
finance_as_code_budget_core.workspace = true
finance_as_code_budget_source_lunchflow = { workspace = true, optional = true }
finance_as_code_budget_source_mbank = { workspace = true, optional = true }
finance_as_code_budget_sink_treeline = { workspace = true, optional = true }
finance_as_code_budget_sink_lunchmoney = { workspace = true, optional = true }
finance_as_code_budget_transformer_lua.workspace = true
finance_as_code_budget_transformer_ai_lua.workspace = true
duckdb = { workspace = true, optional = true, features = ["bundled"] }

[dev-dependencies]
rusty-money.workspace = true
chrono.workspace = true
finance_as_code_utils_hmap.workspace = true
uuid.workspace = true

[package.metadata.cargo-machete]
ignored = ["chrono", "duckdb", "finance_as_code_utils_hmap", "rusty-money", "uuid"]