[workspace.package]
version = "0.0.0-DEV"
edition = "2024"
license = "AGPL-3"

[workspace]
resolver = "3"
members = [
    "crates/api/*",
    "crates/budget/core",
    "crates/budget/root",
    "crates/budget/sink/*",
    "crates/budget/source/*",
    "crates/budget/transformer/*",
    "crates/utils/*",
    "setup/*"
]

[workspace.dependencies]
finance_as_code_budget_core = { path = "crates/budget/core" }
finance_as_code_budget_source_mbank = { path = "crates/budget/source/mbank" }
finance_as_code_budget_source_lunchflow = { path = "crates/budget/source/lunchflow" }
finance_as_code_budget_transformer_lua = { path = "crates/budget/transformer/lua" }
finance_as_code_budget_transformer_ai_lua = { path = "crates/budget/transformer/ai-lua" }
finance_as_code_utils_chrono = { path = "crates/utils/chrono" }
finance_as_code_utils_file_map = { path = "crates/utils/file_map" }
finance_as_code_utils_gemini = { path = "crates/utils/gemini" }
finance_as_code_utils_hmap = { path = "crates/utils/hmap" }
finance_as_code_utils_resilience = { path = "crates/utils/resilience" }
finance_as_code_budget_sink_treeline = { path = "crates/budget/sink/treeline" }
finance_as_code_budget_sink_lunchmoney = { path = "crates/budget/sink/lunchmoney" }
finance_as_code_api_lunchmoney = { path = "crates/api/lunchmoney" }
finance_as_code_api_actual = { path = "crates/api/actual" }

rootcause = { version = "0.12.0" }
bon = "3.8.2"
csv = "1.3"
encoding_rs = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
insta = { version = "1.46.1" }
rusty-money = { version = "0.5.0", features = ["iso", "crypto", "fast", "serde"] }
chrono = { version = "0.4.43", features = ["serde"] }
nonempty-collections = { version = "1.3.0", features = ["serde"] }
rust_decimal = { version = "1.40.0", features = ["macros", "serde"] }
treeline-core = { git = "https://github.com/andrzejressel/treeline", rev = "565ef800f07c38b5ee9696b25bf897a95f7d104c" }
uuid = { version = "1.19.0", features = ["serde", "v4", "v5", "v7", "v8"] }
duckdb = { version = "1.4.3" }
natord = "1.0.9"
mockall = "0.14.0"
googletest = "0.14.2"
tempfile = "3.24.0"
dirs = "6.0.0"
anyhow = "1.0.100"
log = "0.4.29"
colog = "1.4.0"
serde_json = "1.0.149"
schemars = { version = "1.2.1", features = ["derive"] }
itertools = "0.14.0"
httpmock = "0.8.3"
reqwest = {version = "0.13.2", features = ["blocking", "json", "query", "stream"]}
pulumi_gestalt_rust = "0.0.7"
pulumi_gestalt_build = "0.0.7"
serde_yaml = "0.9.34+deprecated"
mlua = { version = "0.11.6", features = ["lua54", "vendored"] }
genai = { version = "0.5.3" }
tokio = { version = "1.43.0", features = ["full"] }
