[package]
name = "finance_as_code_budget_transformer_ai_lua"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
finance_as_code_budget_core.workspace = true
finance_as_code_budget_transformer_lua.workspace = true
finance_as_code_utils_gemini.workspace = true
finance_as_code_utils_file_map.workspace = true
bon.workspace = true
rootcause.workspace = true
log.workspace = true

[dev-dependencies]
googletest.workspace = true
chrono.workspace = true
rusty-money.workspace = true
uuid.workspace = true
tempfile.workspace = true
finance_as_code_utils_gemini = {workspace = true, features = ["mock"]}
finance_as_code_budget_transformer_lua = {workspace = true, features = ["mock"]}
finance_as_code_utils_file_map = { workspace = true, features = ["mock"] }
