[package]
name = "finance_as_code_budget_sink_lunchmoney"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bon.workspace = true
finance_as_code_budget_core.workspace = true
finance_as_code_api_lunchmoney = { workspace = true }
rootcause.workspace = true
log.workspace = true

[dev-dependencies]
googletest.workspace = true
finance_as_code_api_lunchmoney = { workspace = true, features = ["mock"] }
