[package]
name = "finance_as_code_utils_gemini"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
mock = ["mockall"]

[dependencies]
genai.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
bon.workspace = true
rootcause.workspace = true
mockall = { workspace = true, optional = true }

[dev-dependencies]
googletest.workspace = true
httpmock.workspace = true
